FROM xataz/alpine:3.5

MAINTAINER arckosfr <contact@lemark.xyz>

LABEL description="DroneCI base image builder" \
      tags="latest" \
      maintainer="arckosfr <https://github.com/arckosfr>" \
      build_ver="201705261"
	  
RUN apk add -U git \
               bash \
               docker