pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/.docker/config.json:/root/.docker/config.json
    commands:
      - chmod +x .drone/build.sh .drone/push.sh
      - .drone/build.sh
      - .drone/push.sh